### ISSUE TITLE
Make portrait more prominent on character & NPC sheets

### ISSUE THREAD

**Issue by vt-tom** [koboldpress/black-flag#482]
Character Sheet: i would like to see the Portrait of the Character a bit more promiment in the sheet. For now its very small. Maybe you can add an click and open view or an hover effect?

NPC Sheet: I dont like the fact that i can only see the portrait in the biography. I would like to see the picture on every page of the sheet.
But i like that you show the token in die biography. Thats a cool idea.

**Comment by vt-tom** [comment]
Also Adding, if i have a picture which format is not 1:1 it looks not good at the moment:  
![image](https://github.com/koboldpress/black-flag/assets/80099175/31d8131f-f508-46b7-98b1-c77e957ea176)

**Comment by arbron** [comment]
Character & NPC sheet portraits will both open larger when you click them.
