### ISSUE TITLE
Add range & targeting information to activities

### ISSUE THREAD

**Issue by vt-tom** [koboldpress/black-flag#485]
I cant find a Range on the configuration sheet of ranged Attacks.  
NPC Sheet!  

![image](https://github.com/koboldpress/black-flag/assets/80099175/12a36a3b-1634-4f59-94f0-70717968fee6)

**Comment by arbron** [comment]
Currently on spells and weapons have definable range. Adding range and targeting configuration to the activity sheets will come eventually.
