### ISSUE TITLE
 Portrait edit on edit mode

### ISSUE THREAD

**Issue by vt-tom** [koboldpress/black-flag#490]
I really like the new function that i can popout the portrait on click.
But it feels strange if i switch to edit mode that i still have to go to the biography tab to edit the portrait. Maybe you can change the behaviour on clicking the portrait if the sheet is editable?  
![image](https://github.com/koboldpress/black-flag/assets/80099175/6a698594-1465-42c7-acd1-2687b5a5d888)

**Comment by arbron** [comment]
There is an unfortunate issue with Foundry core's behavior for editing images that means if you put two editable images on a sheet that point to the same place they will only update half the time. This can be resolved but it will probably mean bypassing some of the default core behavior.
