### ISSUE TITLE
Additional Prerequisite Options for Talents

### ISSUE THREAD

**Issue by f1gment** [koboldpress/black-flag#531]
There are Talents in the BFRD and TOV that have prerequisites that are not selectable in the prerequisite screen; ability to cast spells off a certain circle or higher, proficiency in a particular skill, character level, etc.

**Comment by arbron** [comment]
- [ ] Access to 2nd-Circle Spell Slots
- [ ] Ability to Cast One or More Cantrips
- [ ] Proficiency with Light or Medium Armor
- [ ] Character 4th Level or Higher
- [ ] Proficiency with at Least One Martial Weapon
- [ ] Proficiency with the Stealth Skill
- [ ] Proficiency with Herbalism Tools

**Comment by arbron** [comment]
Also need to distinguish between "Has any sort of spellcasting" and "Spellcasting Class Feature"
