### ISSUE TITLE
Text Input box cannot be resized for workflow in Configure Item screen

### ISSUE THREAD

**Issue by mikitta23** [koboldpress/black-flag#534]
Text boxes in other text input fields for features, traits, etc, can be resized to allow me to see my full text more easily.  The text input field for the UTILITY Item Configure Item creator does not let me do that.  I would like to be able to resize all my text input boxes to have sufficient room to edit my text comfortably.

**Comment by arbron** [comment]
Can you clarify what screen you mean? Perhaps with a screenshot.

**Comment by mikitta23** [comment]
It's the Utility window.  Maybe it doesn't need one? and I'm
misunderstanding what the Utility description is supposed to be for.


[image: Utility Window.jpg]
