### ISSUE TITLE
Features are not droppable into Class or Lineage creation menu - Bug  Game Breaking

### ISSUE THREAD

**Issue by mikitta23** [koboldpress/black-flag#598]
The creation process to add features to the lineage or class menus is not working.  I cannot create the feature inside the menu, nor can I drag and drop a feature from a file I  created separately.

**Comment by arbron** [comment]
What versions are you running? (Foundry & Black Flag)
<img width="310" alt="Screenshot 2024-06-08 at 10 23 57" src="https://github.com/koboldpress/black-flag/assets/19979839/30bd786b-3b93-4dbb-8815-15d9eba98b64">

**Comment by arbron** [comment]
Hmm, actually, I think I know what is causing this and it is already fixed for the upcoming version.

**Comment by mikitta23** [comment]
Sorry about that ...
[image: Foundry V12 No Mods.jpg]
