### ISSUE TITLE
Allow scaling resource consumption & scaling features

### ISSUE THREAD

**Issue by arbron** [koboldpress/black-flag#617]

**Comment by cmbernard333** [comment]
Is this a newer way to track scaling resources? I noticed with version 35 that using something like `@scale.warlock.pact-magic-uses` no longer resolves inside of a separate feature for the maximum usage.

**Comment by arbron** [comment]
> Is this a newer way to track scaling resources? I noticed with version 35 that using something like `@scale.warlock.pact-magic-uses` no longer resolves inside of a separate feature for the maximum usage.

That's a bug that will be fixed in the next version. This is for allowing non-spell features to be "upcast" to consume more resources (so for like Lay On Hands you can choose how many HP to heal).
