### ISSUE TITLE
Update [[/attack]] enricher to concatenate the ability modifier and proficiency bonus when rendered

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#675]
Right now, if you use that enricher, it renders as +4+4 (ability mod and PB), which does not look good in the text.  It would be better if it simply displays as a single value by default, e.g., +8.  If content creators want to break out the attack bonuses, perhaps a value can be added to the enricher to render the bonus values separately, e.g. [[/attack format=long]].

~Submitted by Clayton Thomson

**Comment by arbron** [comment]
This is intended, unfortunately Foundry's built in ability to simplify rolls is limited so it will need some custom handling.
