### ISSUE TITLE
Add a journal css class to remove borders from things like headlines and images

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#677]
To remove borders from elements like headlines and images, we can add a CSS class called .noborder with the property `border:none;.` 

There is already a CSS class with the same name in either the 5e system CSS or the core CSS that can be used in journals. In the BF system, I currently have to add an inline CSS declaration to remove unwanted borders in journals. While this solution works fine, it may be more efficient to have it in the system CSS.

_~Submitted by Clayton Thomson_

**Comment by arbron** [comment]
Removed the borders from images and added a number of utility classes to help with placement:

<img width="251" alt="Screenshot 2024-07-24 at 19 36 20" src="https://github.com/user-attachments/assets/5d4be15e-56c0-4e91-b3ee-ed108698d95a">

What heading borders do you need to remove (they should all be set up to match the design language used in the official books)?

**Comment by secondworldpublishing** [comment]
I would love to have a class that allows creators to remove borders on the H tags accessible in the journal (prosemirror).  I think h1, h2, and h3 render borders underneath the text.  I'm not advocating that they be removed from the system or core FVTT CSS.  I just like to have a class I can use to remove the border in certain cases.  Even with module-level CSS, higher-level CSS renders an unwanted border anyway.  In 5e, I use a class called "noborder" that removes borders underneath text and around images.  I use that class from time-to-time.  Anyway, I hope I answered your question.
