### ISSUE TITLE
Lair Actor unusable for lair actions and activities

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#679]
Lair Actor - Lair Actions - When create Lair Actions, continual errors are being thrown into the JavaScript console (log attached).  Things worked fine until I wanted to make some edits. The best way to recreate this is to delete one of the lair actions, then recreate from scratch.  These errors started as soon as I added a Lair Action and additional errors are being thrown when I added an activity.  Once the activity was created, I could not open the activity to configure it.  JSON of Lair actor is also attacks.  I happy to demo the issue over Zoom if needed.

[localhost-1721950084214.log](https://github.com/user-attachments/files/16384492/localhost-1721950084214.log)

[fvtt-Actor-solar's-lair-MmGOUGIEsJ71YtUw.json](https://github.com/user-attachments/files/16384494/fvtt-Actor-solar.s-lair-MmGOUGIEsJ71YtUw.json)

**Comment by arbron** [comment]
There seems to be an error with the `AttackActivity` specifically. Cannot see any error with just adding a lair action without any activities.

**Comment by secondworldpublishing** [comment]
Thank you.
