### ISSUE TITLE
Actor - Activity - System version migration may be removing activities from the NPC actor

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#735]
I’ve seen this with NPCs I created and actors created for the BF system. I have no way to recreate this, but it is happening intermittently.  The system I've seen this issue is in 0.10.044.

So far, I've seen Save and Utility actions removed from the NPC actor and spells configured in the NPC actor.

Note: Because content production-impacting bugs surfaced in x.041, x.042, and x.043, I needed to revert back to x.040 for each system update except x.044.  It is possible that the activity was stripped due to the reversion.  Not sure.

**Comment by secondworldpublishing** [comment]
I'm seeing the removal of any activity, not just the ones I mentioned above.  Also, it seems to occur on creatures created in 0.10.040, which is most of them.  In QA, to correct the issue, I have to rebuild the entire activity.

Again, I don't know if this issue results from updating the system or if updating to x.041, x.042, and x.043, then reverting to x.040.

**Comment by secondworldpublishing** [comment]
I did some testing this morning, and it appears that the activities are being stripped when upgrading from 0.10.041 to 0.10.042.  Please see attached screenshots.  

![Test Adult Red Dragon BFRD 0 10 042](https://github.com/user-attachments/assets/d707bfa2-2877-4f0d-8630-5a498ab8223d)
![Test Adult Red Dragon Lair BFRD 0 10 040](https://github.com/user-attachments/assets/c2849168-d69d-4cae-9783-327cc92e42be)
![Test Adult Red Dragon Lair BFRD 0 10 041](https://github.com/user-attachments/assets/0ef32be8-3472-4b6a-9c3c-b075f9a3fb59)
![Test Adult Red Dragon Lair BFRD 0 10 042](https://github.com/user-attachments/assets/5c09996c-72b2-4521-9b85-58e0efa85d1d)
![Test Bugbear Champion BFRD 0 10 040](https://github.com/user-attachments/assets/ca09be62-7686-4e2d-9f03-62a7b0674a9d)
![Test Bugbear Champion BFRD 0 10 041](https://github.com/user-attachments/assets/5ad6b311-7354-4910-a490-0bf1ee19f373)
![Test Bugbear Champion BFRD 0 10 042](https://github.com/user-attachments/assets/ce77a50a-f82e-4ff0-a496-68a4b230bf33)
![Test Fire Elemental BFRD 0 10 040](https://github.com/user-attachments/assets/b93a1b11-9bc0-405b-b06c-812c1b26fd2e)
![Test Fire Elemental BFRD 0 10 041](https://github.com/user-attachments/assets/fbf81f40-3e20-4f1f-b66a-3ef0deb98f05)
![Test Fire Elemental BFRD 0 10 042](https://github.com/user-attachments/assets/75a46b38-c7d4-4501-bf75-12f57b02b647)
![Test Purple Worm BFRD 0 10 040](https://github.com/user-attachments/assets/a26d1c70-eeb4-48fe-ae50-9d08299a46e1)
![Test Purple Worm BFRD 0 10 041](https://github.com/user-attachments/assets/8cb2dea6-6975-41ee-ab45-17106b0a214b)
![Test Purple Worm BFRD 0 10 042](https://github.com/user-attachments/assets/a313d817-71d4-4565-a352-48bb2bab4bb8)
![Test Adult Red Dragon BFRD 0 10 040](https://github.com/user-attachments/assets/2f7bb19f-c22b-403c-a421-282767a269b7)
![Test Adult Red Dragon BFRD 0 10 041](https://github.com/user-attachments/assets/b5b7afb3-0785-4322-a0f7-2cda53910326)

**Comment by arbron** [comment]
@secondworldpublishing Can you provide JSON for some of these (before is more useful)?

**Comment by arbron** [comment]
Nevermind, I figured it out. Seems like a activity type migration that was being performed was only happening properly on items in the world, not in compendiums.
