### ISSUE TITLE
CON not adding to hit points

### ISSUE THREAD

**Issue by dukeotaku** [koboldpress/black-flag#754]
A player has reported her CON bonus is not being added to her HP average when leveling up.

**Comment by dukeotaku** [comment]
Is there a way we can be able to edit the Max HP box? I didnt see a way to

**Comment by arbron** [comment]
Constitution seems to be properly adding to HP on my end:

<img width="230" alt="Screenshot 2024-09-20 at 14 27 38" src="https://github.com/user-attachments/assets/99789ae0-bae3-4d78-9839-05836d29f4d8">

<img width="218" alt="Screenshot 2024-09-20 at 14 27 48" src="https://github.com/user-attachments/assets/043ac7ba-a06f-441a-9d5d-761473d2122a">

Is this only for that player's character or can you reproduce the issue on all the characters?

Max HP isn't currently directly editable, it has to be set during level up.

**Comment by dukeotaku** [comment]
I just created two characters and leveled them: one a dwarf and the other a homebrew we added for the player. It is correct for the dwarf but not the homebrew lineage. Is there some option I may have missed? Or do I need to update the code?

**Comment by arbron** [comment]
> I just created two characters and leveled them: one a dwarf and the other a homebrew we added for the player. It is correct for the dwarf but not the homebrew lineage. Is there some option I may have missed? Or do I need to update the code?

Hmm, lineage shouldn't have any effect on hit points. Is the only different between the two actors the lineage? Any errors in the developer console?

It might help if you could send over a JSON of the affected actors.

**Comment by dukeotaku** [comment]
Here is her json. When I leveled my test characters just now, the hp values are correct for level 2. She leveled to 7 and she took the average each level. I tried to look at the code but couldnt tell where she says it didnt add her CON modifier. 

[fvtt-Actor-magreth-17bzfIm3CyOMNCh9.json](https://github.com/user-attachments/files/17087897/fvtt-Actor-magreth-17bzfIm3CyOMNCh9.json)
