### ISSUE TITLE
Actor - Activities - Enhancement - Add damage value to denote HP Max Reduction & HP damage

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#770]
As part of the damage type dropdown in activities and the value displayed in the damage enricher, please add the following values or equivalent “HP Max Reduction” and "HP" to denote this specific type of damage from other damage types.

**Comment by arbron** [comment]
Note to self: Need to fix damage enricher to ensure the proper roll type is performed

```
// Applies max HP damage
[[/damage 1d4 max]]

// Applies max HP healing
[[/healing 1d4 max]]
```
