### ISSUE TITLE
Actor>NPC - Errors thrown when trying to access sheet on a scene and Actor Directory

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#867]
Certain NPC Actors are throwing errors when dragged onto a scene or double-clicked from the Actor Directory.  You are also unable to access the Actor sheet in both cases.  See attached actor sheets.  I’m not sure what the error means, but I have not seen this in previous BF builds and this issue is not universal with all actors.

When the actor is on the scene and you double-click it, it throws the following error:

foundry.js:655 
Error: An error occurred while rendering NPCSheet 61. One of original or other are not Objects!
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13
Caused by: Error: One of original or other are not Objects!
    at mergeObject (foundry-esm.js:3324:13)
    at _mergeUpdate (foundry-esm.js:3388:14)
    at mergeObject (foundry-esm.js:3345:41)
    at _mergeUpdate (foundry-esm.js:3388:14)
    at mergeObject (foundry-esm.js:3345:41)
    at _mergeUpdate (foundry-esm.js:3388:14)
    at Object.mergeObject (foundry-esm.js:3345:41)
    at NPCSheet._render (foundry.js:5831:19)
    at NPCSheet._render (foundry.js:6572:17)
    at NPCSheet._render (foundry.js:7158:17)
	onError	@	foundry.js:655
	(anonymous)	@	foundry.js:5795
	Promise.catch		
	render	@	foundry.js:5793
	_onClickLeft2	@	foundry.js:61477
	callback	@	foundry.js:30834
	#handleClickLeft2	@	foundry.js:31057
	#handleLeftDown	@	foundry.js:31016
	#handlePointerDown	@	foundry.js:30981
	notifyListeners	@	EventBoundary.ts:1454
	notifyTarget	@	EventBoundary.ts:662
	propagate	@	EventBoundary.ts:299
	dispatchEvent	@	EventBoundary.ts:210
	mapPointerDown	@	EventBoundary.ts:683
	mapEvent	@	EventBoundary.ts:231
	onPointerDown	@	EventSystem.ts:373

![Screenshot 2024-12-07 at 9 04 19 AM](https://github.com/user-attachments/assets/580e0b2d-c40d-4303-bcf8-44853e42ebfc)

When double-clicking on the actor in the Actor Directory, the actor sheet will not open and throws the following error:

Error: An error occurred while rendering NPCSheet 116. getPluralRules is not defined
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13Caused by: ReferenceError: getPluralRules is not defined
    at NPCSheet.prepareActions (npc-sheet.mjs:66:5)
    at async NPCSheet.getData (base-actor-sheet.mjs:88:3)
    at async NPCSheet.getData (npc-sheet.mjs:26:19)
    at async NPCSheet._render (foundry.js:5838:18)
    at async NPCSheet._render (foundry.js:6572:5)
    at async NPCSheet._render (foundry.js:7158:5)

![Screenshot 2024-12-07 at 9 11 28 AM](https://github.com/user-attachments/assets/2790129d-ceb9-4cf6-8669-80a57e365c4e)

[fvtt-Actor-adult-red-dragon-lich-RabRwsXg3aaCx2g0.json](https://github.com/user-attachments/files/18049290/fvtt-Actor-adult-red-dragon-lich-RabRwsXg3aaCx2g0.json)

[fvtt-Actor-adult-blue-dragon-zombie-HL2WN2xrNwKK8pTQ.json](https://github.com/user-attachments/files/18049291/fvtt-Actor-adult-blue-dragon-zombie-HL2WN2xrNwKK8pTQ.json)

**Comment by arbron** [comment]
Fixed the second issue, but haven't been able to reproduce the first one.

**Comment by secondworldpublishing** [comment]
The second error is thrown when you drag the actor onto a scene, then double-click it to open.  The same error is thrown when double-clicking on the actor from the actors directory.

**Comment by secondworldpublishing** [comment]
[Issue 867 Demo.webm](https://github.com/user-attachments/assets/6e55632e-413f-4e66-a3ac-c3b382699c64)

**Comment by arbron** [comment]
> Issue.867.Demo.webm

That's the one I already fixed, its the other error I haven't been able to reproduce.

**Comment by arbron** [comment]
Closing this issue for tracking purposes, feel free to refile if you can reproduce the first issue after the upcoming release.

**Comment by secondworldpublishing** [comment]
Sounds fine.  I'm not able to recreate the second error as well.
