### ISSUE TITLE
Actors > Vehicles: Bonus Actions and Reactions need a generic text box like what is available in Actions

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#872]
Like Actions, Reactions and Bonus Actions may have some flavor text. A text box should to be added to contain such text like in Actions as an enhancement to the Vehicle Actor.

![Screenshot 2024-12-07 at 10 07 54 AM](https://github.com/user-attachments/assets/3f247b7d-1fb3-49fe-9096-0327c076151a)

**Comment by arbron** [comment]
Vehicles only have actions, not bonus actions or reactions. If you have any example vehicles that do otherwise feel free to show me.

**Comment by secondworldpublishing** [comment]
Winged Dragon Vehicle has a reaction. Per KP, it is possible that future vehicles may have similar generic text to restrict the use of a bonus action.

[fvtt-Actor-winged-dragon-WMYZewAervWnyDkL.json](https://github.com/user-attachments/files/18049651/fvtt-Actor-winged-dragon-WMYZewAervWnyDkL.json)
