### ISSUE TITLE
Actors>Vehicle - Enhancement to support both Siege Weapon Resilience and Vehicle Resilience

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#873]
Siege Weapon Resilience should be baked into the Vehicle Actor like Vehicle Resilience.  Additionally, vehicle actors need some radio-button or drop-down affordance to toggle on/off either Vehicle Resilience or Siege Weapon Resilience - say in size configuration - since they are identical so the correct type of resilience is displayed in the Actor UI.

![Screenshot 2024-12-07 at 10 10 38 AM](https://github.com/user-attachments/assets/88e91e16-1627-40c1-acbc-717645b12a92)

**Comment by arbron** [comment]
Vehicle resilience is just an item that is automatically added to vehicles, so you can just delete it if you don't want it.

**Comment by secondworldpublishing** [comment]
Yikes!  I didn't even look in the effects tab.
