### ISSUE TITLE
Add siege weapon actor type

### ISSUE THREAD

**Issue by secondworldpublishing** [koboldpress/black-flag#874]
Vehicle actors need a vehicle type of “Object” as an enhancement.  

Further, if there are no values for dimensions, the UI that shows the dimensions should be removed.

![Screenshot 2024-12-07 at 10 14 49 AM](https://github.com/user-attachments/assets/a0e25bcf-1af6-4afd-b46e-a21479ace5cf)

![Screenshot 2024-12-07 at 10 15 04 AM](https://github.com/user-attachments/assets/85ec67f6-c7f0-4103-ae74-f3e21fd412fb)

**Comment by arbron** [comment]
Siege weapons should probably be handled by a new actor type, not the vehicle type, because they don't have passengers, crew, cargo, speed, or initiative.

**Comment by secondworldpublishing** [comment]
I agree. For now, I built them as vehicles, which seems to work fine for now. When you have a chance to release the new actor type, it is simple enough for me to change these over.

**Comment by secondworldpublishing** [comment]
Winged Dragon Vehicle has a reaction.  Per KP, it is possible that future vehicles may have similar generic text to restrict the use of a bonus action.

[fvtt-Actor-winged-dragon-WMYZewAervWnyDkL.json](https://github.com/user-attachments/files/18049651/fvtt-Actor-winged-dragon-WMYZewAervWnyDkL.json)
